/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacionFrames;

import dtos.EventoDTO;
import dtos.UsuarioDTO;
import excepciones.NegocioException;
import interfaces.IEventoBO;
import interfaces.IUsuarioBO;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import negocio.EventoBO;
import negocio.UsuarioBO;
import utilidades.Forms;

/**
 *
 * @author pauli
 */
public class FrmAdministrador extends javax.swing.JFrame {

    private UsuarioDTO usuarioLoggeado;
    private IEventoBO eventobo;
    private IUsuarioBO usuariobo;
    private EventoDTO eventoCreando;

    /**
     * Creates new form FrmBoletosAdquiridos
     */
    public FrmAdministrador(UsuarioDTO usuarioLoggeado) {
        initComponents();
        this.usuarioLoggeado = usuarioLoggeado;
        this.eventobo = new EventoBO();
        this.usuariobo = new UsuarioBO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAsignarBoletos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnGuardarEvento = new javax.swing.JButton();
        txtLocalidad = new javax.swing.JTextField();
        txtVenue = new javax.swing.JTextField();
        txtFilas = new javax.swing.JTextField();
        txtAsientos = new javax.swing.JTextField();
        labelCapacidad = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Administrador");

        btnAsignarBoletos.setText("Asignar boletos");
        btnAsignarBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarBoletosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Crear Evento");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Fecha:");

        jLabel5.setText("Localidad:");

        jLabel6.setText("Numero de filas:");

        jLabel7.setText("Numero de asientos por fila:");

        jLabel8.setText("Capacidad:");

        jLabel9.setText("Venue:");

        btnGuardarEvento.setText("Guardar Evento");
        btnGuardarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEventoActionPerformed(evt);
            }
        });

        txtFilas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilasKeyReleased(evt);
            }
        });

        txtAsientos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAsientosKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnAsignarBoletos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarEvento)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVenue, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCapacidad)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtAsientos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                .addComponent(txtFilas, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtVenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(labelCapacidad))
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(btnAsignarBoletos)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarBoletosActionPerformed
        Forms.cargarForm(new FrmAsignarBoletos(usuarioLoggeado), this);
    }//GEN-LAST:event_btnAsignarBoletosActionPerformed

    private void btnGuardarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEventoActionPerformed
        this.crearEvento();
    }//GEN-LAST:event_btnGuardarEventoActionPerformed

    private void txtFilasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilasKeyReleased
        actualizarCapacidad();
        validarEnterosFilas();
    }//GEN-LAST:event_txtFilasKeyReleased

    private void txtAsientosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAsientosKeyReleased
        actualizarCapacidad();
        validarEnterosAsientos();
    }//GEN-LAST:event_txtAsientosKeyReleased

    private void crearEvento() {
        eventoCreando = new EventoDTO();
        Date mFecha = jDateChooser1.getDate();
        try {

            // Inicializamos una bandera para identificar si hay campos vacíos
            boolean hayCamposVacios = false;
            StringBuilder camposFaltantes = new StringBuilder("Por favor, completa los siguientes campos:\n");

            // Verificar cada campo
            if (txtNombre.getText().isEmpty()) {
                camposFaltantes.append("- Nombre del evento\n");
                hayCamposVacios = true;
            }

            if (mFecha == null) {
                camposFaltantes.append("- Fecha del evento\n");
                hayCamposVacios = true;
            }

            if (txtLocalidad.getText().isEmpty()) {
                camposFaltantes.append("- Localidad del evento\n");
                hayCamposVacios = true;
            }

            if (txtVenue.getText().isEmpty()) {
                camposFaltantes.append("- Venue del evento\n");
                hayCamposVacios = true;
            }

            if (txtFilas.getText().isEmpty()) {
                camposFaltantes.append("- Número de filas\n");
                hayCamposVacios = true;
            }

            if (txtAsientos.getText().isEmpty()) {
                camposFaltantes.append("- Número de asientos por fila\n");
                hayCamposVacios = true;
            }

            // Si hay al menos un campo vacío, mostramos el mensaje
            if (hayCamposVacios) {
                JOptionPane.showMessageDialog(this, camposFaltantes.toString(), "Campos Vacíos", JOptionPane.ERROR_MESSAGE);
            }

            Calendar cal = Calendar.getInstance();
            cal.setTime(mFecha);
            int añoNacimiento = cal.get(Calendar.YEAR);
            int añoActual = Calendar.getInstance().get(Calendar.YEAR);
            int edad = añoActual - añoNacimiento;

            eventoCreando.setNombre(txtNombre.getText());
            java.sql.Date fechaSQL = new java.sql.Date(mFecha.getTime());
            eventoCreando.setFecha(fechaSQL);
            eventoCreando.setLocalidad(txtLocalidad.getText());
            eventoCreando.setVenue(txtVenue.getText());

            this.actualizarCapacidad();

            if (eventobo.existeEvento(eventoCreando.getNombre())) {
                JOptionPane.showMessageDialog(this, "El nombre del evento ya está registrado. Por favor, use otro.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }

            this.guardarEvento();

            JOptionPane.showMessageDialog(this, "Exito!, se ha creado el evento correctamente.");

            this.limpiarTextbox();
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error durante la operacion, intentelo denuevo", "Error!", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void guardarEvento() {
        try {
            this.eventobo.agregar(eventoCreando);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "El usuairo no ha podido registrarse correctamente.", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void actualizarCapacidad() {
        try {
            int filas = Integer.parseInt(txtFilas.getText());
            int asientos = Integer.parseInt(txtAsientos.getText());
            int capacidad = filas * asientos;
            labelCapacidad.setText(String.valueOf(capacidad));
            eventoCreando.setCapacidad(capacidad); // Actualizar el objeto eventoCreando
        } catch (NumberFormatException ex) {
            // Si el usuario no ha ingresado números válidos, puedes manejarlo aquí
            labelCapacidad.setText("0");  // Muestra 0 si los valores no son válidos
        }
    }

    private boolean validarEnterosFilas() {
    boolean hayCamposVacios = false;
    StringBuilder camposFaltantes = new StringBuilder("Por favor, completa los siguientes campos:\n");

    // Validación del campo de filas
    if (txtFilas.getText().isEmpty()) {
        camposFaltantes.append("- Número de filas\n");
        hayCamposVacios = true;
    } else {
        try {
            Integer.parseInt(txtFilas.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un número válido para el número de filas.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            return false; // Indicar que la validación falló
        }
    }

    // Mostrar mensaje si hay campos vacíos
    if (hayCamposVacios) {
        JOptionPane.showMessageDialog(this, camposFaltantes.toString(), "Campos Vacíos", JOptionPane.ERROR_MESSAGE);
        return false; // Indicar que la validación falló
    }

    return true; // Indicar que la validación fue exitosa
}
private boolean validarEnterosAsientos() {
    boolean hayCamposVacios = false;
    StringBuilder camposFaltantes = new StringBuilder("Por favor, completa los siguientes campos:\n");

    // Validación del campo de filas
    if (txtAsientos.getText().isEmpty()) {
        camposFaltantes.append("- Número de filas\n");
        hayCamposVacios = true;
    } else {
        try {
            Integer.parseInt(txtAsientos.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un número válido para el número de filas.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            return false; // Indicar que la validación falló
        }
    }

    // Mostrar mensaje si hay campos vacíos
    if (hayCamposVacios) {
        JOptionPane.showMessageDialog(this, camposFaltantes.toString(), "Campos Vacíos", JOptionPane.ERROR_MESSAGE);
        return false; // Indicar que la validación falló
    }

    return true; // Indicar que la validación fue exitosa
}
    /**
     * Limpia los campos de texto.
     */
    public void limpiarTextbox() {
        txtNombre.setText("");
        jDateChooser1.setDate(null);
        txtLocalidad.setText("");
        txtVenue.setText("");
        txtFilas.setText("");
        txtAsientos.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarBoletos;
    private javax.swing.JButton btnGuardarEvento;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelCapacidad;
    private javax.swing.JTextField txtAsientos;
    private javax.swing.JTextField txtFilas;
    private javax.swing.JTextField txtLocalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtVenue;
    // End of variables declaration//GEN-END:variables
}
