/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacionFrames;

import dtos.BoletoDTO;
import dtos.EventoDTO;
import dtos.UsuarioDTO;
import excepciones.NegocioException;
import interfaces.IBoletoBO;
import interfaces.IEventoBO;
import interfaces.ITransaccionBO;
import interfaces.IUsuarioBO;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.BoletoBO;
import negocio.EventoBO;
import negocio.TransaccionBO;
import negocio.UsuarioBO;
import utilidades.Forms;

/**
 * Clase que representa la interfaz gráfica del formulario para la venta de
 * boletos. Permite a los usuarios realizar compras de boletos para eventos,
 * visualizar detalles de los boletos disponibles y gestionar la transacción de
 * compra.
 *
 * @author Cristopher Alberto Elizalde Andrade - 240005
 * @author Paulina Rodríguez Rodríguez Rayos - 117262
 */
public class FrmBoletosVenta extends javax.swing.JFrame {

    private UsuarioDTO usuarioLoggeado;
    private ITransaccionBO transaccionbo;
    private IEventoBO eventobo;
    private IUsuarioBO usuariobo;
    private IBoletoBO boletobo;

    /**
     * Creates new form FrmBoletosVenta
     */
    public FrmBoletosVenta(UsuarioDTO usuarioLoggeado) {
        initComponents();
        this.usuarioLoggeado = usuarioLoggeado;
        this.transaccionbo = new TransaccionBO();
        this.usuariobo = new UsuarioBO();
        this.eventobo = new EventoBO();
        this.boletobo = new BoletoBO();
        this.cargarBoletosEnVenta();
        this.setLocationRelativeTo(this);
    }

    private void cargarBoletosEnVenta() {
        List<BoletoDTO> boletosEnVenta = null;
        try {
            // Consultar los boletos que el usuario ha puesto en venta
            boletosEnVenta = boletobo.consultarBoletosEnVenta(usuarioLoggeado.getIdUsuario());
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Llenar la tabla con los boletos en venta
        llenarTablaBoletosEnVenta(boletosEnVenta);
    }

    private void llenarTablaBoletosEnVenta(List<BoletoDTO> boletosEnVenta) {
        DefaultTableModel modeloTabla = (DefaultTableModel) this.tblBoletos.getModel();

        if (modeloTabla.getRowCount() > 0) {
            for (int i = modeloTabla.getRowCount() - 1; i > -1; i--) {
                modeloTabla.removeRow(i);
            }
        }

        if (boletosEnVenta != null) {
            boletosEnVenta.forEach(row -> {
                Object[] fila = new Object[9];
                fila[0] = row.getNumSerie();
                fila[1] = row.getFila();
                fila[2] = row.getAsiento();
                Object[] detallesEvento = consultarDetallesEventoPorId(row.getIdEvento());
                if (detallesEvento != null) {
                    fila[3] = detallesEvento[0];
                    fila[4] = detallesEvento[1];
                    fila[5] = detallesEvento[2];
                    fila[6] = detallesEvento[3];
                }
                fila[7] = row.getPrecioReventa();
                fila[8] = row.getIdBoleto();
                modeloTabla.addRow(fila);
            });
        }
    }

    private Object[] consultarDetallesEventoPorId(int idEvento) {
        try {
            EventoDTO evento = eventobo.consultar(idEvento);

            Object[] detallesEvento = new Object[6];
            detallesEvento[0] = evento.getNombre();
            detallesEvento[1] = evento.getLocalidad();
            detallesEvento[2] = evento.getVenue();
            detallesEvento[3] = evento.getFecha();
            return detallesEvento;
        } catch (NegocioException ex) {
            Logger.getLogger(FrmMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBoletos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblBoletos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Serie", "Fila", "Asiento", "Evento", "Localidad", "Venue", "Fecha", "Precio de venta", "idBoleto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBoletos);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Boletos en venta");

        jButton1.setText("Quitar a la venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnRegresar))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = tblBoletos.getSelectedRow();
            if (selectedRow != -1) {
                int idBoleto = (int) tblBoletos.getValueAt(selectedRow, 8);
                boletobo.actualizarBoletoParaReventa(idBoleto);
                JOptionPane.showMessageDialog(this, "El boleto ya no esta a la venta.");
                cargarBoletosEnVenta();
            }

        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace(); // Para depuración
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Forms.cargarForm(new FrmMenuPrincipal(usuarioLoggeado), this);
    }//GEN-LAST:event_btnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBoletos;
    // End of variables declaration//GEN-END:variables
}
