/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacionFrames;

import dtos.UsuarioDTO;
import excepciones.NegocioException;
import interfaces.IBoletoBO;
import java.util.Date;
import javax.swing.JOptionPane;
import negocio.BoletoBO;

/**
 *
 * @author pauli
 */
public class FrmVenderBoleto extends javax.swing.JFrame {

    private UsuarioDTO usuarioLoggeado;
    private IBoletoBO boletobo;
    private String numSerie;
    private int fila;
    private int asiento;
    private String nombreEvento;

    /**
     * Creates new form FrmVenderBoleto
     */
    public FrmVenderBoleto(UsuarioDTO usuarioLoggeado, String numSerie, int fila, int asiento, String nombreEvento) {
        initComponents();

        this.usuarioLoggeado = usuarioLoggeado;
        this.numSerie = numSerie;
        this.fila = fila;
        this.asiento = asiento;
        this.nombreEvento = nombreEvento;
        this.boletobo = new BoletoBO();

        // Llenar los campos con los datos del boleto
        lblnumero.setText(numSerie);
        lblfila.setText(String.valueOf(fila));
        lblasiento.setText(String.valueOf(asiento));
        lblevento.setText(nombreEvento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblnumero = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblfila = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblasiento = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblevento = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Poner en venta boleto");

        jLabel2.setText("Numero Serie:");

        lblnumero.setText("obtenerserie");

        jLabel4.setText("Fila:");

        lblfila.setText("obtenerfila");

        jLabel6.setText("Asiento:");

        lblasiento.setText("obtenerasiento");

        jLabel8.setText("Evento:");

        lblevento.setText("obtener evento");

        jLabel10.setText("Precio de reventa:");

        jLabel11.setText("Fecha limite de venta: ");

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)))
                            .addComponent(jLabel2))
                        .addGap(354, 354, 354))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblfila)
                                    .addComponent(lblnumero)
                                    .addComponent(lblasiento)
                                    .addComponent(lblevento))))
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(84, 84, 84))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(94, 94, 94)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(199, 199, 199))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblnumero))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblfila))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblasiento)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblevento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        try {
//            double precioOriginal = boletobo.obtenerPrecioOriginal(numSerie); // Método para obtener el precio original
//            double nuevoPrecio = Double.parseDouble(txtPrecio.getText());
//
//            // Validar que el nuevo precio no exceda el 3% del precio original
//            if (nuevoPrecio > precioOriginal * 1.03) {
//                JOptionPane.showMessageDialog(this, "El precio no debe exceder el 3% del precio original.");
//                return;
//            }
//
//            // Obtener la fecha límite
//            Date fechaLimite = jDateChooser1.getDate();
//
//            // Llamar al procedimiento para realizar la reventa
//            transaccionbo.realizarReventa(numSerie, nuevoPrecio, fechaLimite, usuarioLoggeado.getId());
//
//            JOptionPane.showMessageDialog(this, "Reventa exitosa.");
//            this.dispose(); // Cerrar el frame después de la venta
//        } catch (NegocioException ex) {
//            JOptionPane.showMessageDialog(this, "Error al realizar la reventa.");
//            Logger.getLogger(FrmVenderBoleto.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblasiento;
    private javax.swing.JLabel lblevento;
    private javax.swing.JLabel lblfila;
    private javax.swing.JLabel lblnumero;
    // End of variables declaration//GEN-END:variables
}
